package org.onebusaway.nyc.transit_data_manager.config.model.jaxb;

/**
 * Response message generated by api call after executing request method.
 * @author abelsare
 *
 */
public class Message {
	private String status;
	private String messageText;

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * @return the messageText
	 */
	public String getMessageText() {
		return messageText;
	}

	/**
	 * @param messageText the messageText to set
	 */
	public void setMessageText(String messageText) {
		this.messageText = messageText;
	}

}
