//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2011.09.14 at 03:21:42 PM EDT
//

package org.onebusaway.nyc.transit_data_manager.model.xml.busAssignment;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Table" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BUS_NUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="AGENCY" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="DEPOT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"table"})
@XmlRootElement(name = "NewDataSet")
public class NewDataSet {

  @XmlElement(name = "Table", required = true)
  protected List<NewDataSet.Table> table;

  /**
   * Gets the value of the table property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the table property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getTable().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link NewDataSet.Table }
   * 
   * 
   */
  public List<NewDataSet.Table> getTable() {
    if (table == null) {
      table = new ArrayList<NewDataSet.Table>();
    }
    return this.table;
  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained
   * within this class.
   * 
   * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BUS_NUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="AGENCY" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="DEPOT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"busnumber", "agency", "depot"})
  public static class Table {

    @XmlElement(name = "BUS_NUMBER")
    protected int busnumber;
    @XmlElement(name = "AGENCY")
    protected int agency;
    @XmlElement(name = "DEPOT", required = true)
    protected String depot;

    /**
     * Gets the value of the busnumber property.
     * 
     */
    public int getBUSNUMBER() {
      return busnumber;
    }

    /**
     * Sets the value of the busnumber property.
     * 
     */
    public void setBUSNUMBER(int value) {
      this.busnumber = value;
    }

    /**
     * Gets the value of the agency property.
     * 
     */
    public int getAGENCY() {
      return agency;
    }

    /**
     * Sets the value of the agency property.
     * 
     */
    public void setAGENCY(int value) {
      this.agency = value;
    }

    /**
     * Gets the value of the depot property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDEPOT() {
      return depot;
    }

    /**
     * Sets the value of the depot property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDEPOT(String value) {
      this.depot = value;
    }

  }

}
