//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.09 at 11:10:39 AM EDT 
//


package hello;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CcAdherencePerformance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CcAdherencePerformance">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="insert-local-information-elements-here" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CcAdherencePerformance", propOrder = {
    "insertLocalInformationElementsHere"
})
public class CcAdherencePerformance {

    @XmlElement(name = "insert-local-information-elements-here")
    protected String insertLocalInformationElementsHere;

    /**
     * Gets the value of the insertLocalInformationElementsHere property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsertLocalInformationElementsHere() {
        return insertLocalInformationElementsHere;
    }

    /**
     * Sets the value of the insertLocalInformationElementsHere property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsertLocalInformationElementsHere(String value) {
        this.insertLocalInformationElementsHere = value;
    }

}
