//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.09 at 11:10:39 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tcip-3-0-5-local")
package hello;
